import React from "react";
import { NavLink } from "react-router-dom";

export default function Cookie() {
  return (
    <div class="bg-[#F7F7F7] h-[90vh] px-3 py-3 lg:py-10 lg:px-10 ">
       <h2 className="font-semibold text-[24px] leading-[29px]">
       Cookie Policy
      </h2>
      <div className="bg-[#FFFFFF] border rounded-[10px] border-[#E4E4E4] mt-10 py-3 px-3  lg:py-6 lg:px-6 overflow-auto scroll-box">
        <>
          <h1
          className="font-semibold text-[24px] leading-[29px]"
            style={{
              textTransform: "uppercase",
              color: "#000000",
              textAlign: "center",
            }}
          >
            Cookie Policy
          </h1>
          <p style={{ textAlign: "center" }}>Updated at September 12th, 2024</p>
          <br />
          <br />
          <h2 className="font-semibold text-[24px] leading-[29px]">Definitions and key terms</h2>
          <p  className="font-semibold text-[15px] leading-[29px]">
            To help explain things as clearly as possible in this Cookie Policy,
            every time any of these terms are referenced, are strictly defined
            as:
          </p>
          <br />
          <ul>
            <li>
              Cookie: small amount of data generated by a website and saved by
              your web browser. It is used to identify your browser, provide
              analytics, remember information about you such as your language
              preference or login information.
            </li>
            <li>
              Company: when this policy mentions “Company,” “we,” “us,” or
              “our,” it refers to JB Sittner Trucking, that is responsible for
              your information under this Cookie Policy.
            </li>
            <li>
              Device: any internet connected device such as a phone, tablet,
              computer or any other device that can be used to visit JB Sittner
              Trucking and use the services.
            </li>
            <li>
              Personal Data: any information that directly, indirectly, or in
              connection with other information — including a personal
              identification number — allows for the identification or
              identifiability of a natural person.
            </li>
            <li>
              Service: refers to the service provided by JB Sittner Trucking as
              described in the relative terms (if available) and on this
              platform.
            </li>
            <li>
              Third-party service: refers to advertisers, contest sponsors,
              promotional and marketing partners, and others who provide our
              content or whose products or services we think may interest you.
            </li>
            <li>
              Website: JB Sittner Trucking’s site, which can be accessed via
              this URL: https://www.jbsittnertruckingllc.com/
            </li>
            <li>
              You: a person or entity that is registered with JB Sittner
              Trucking to use the Services.
            </li>
          </ul>
          <br />
          <h2    className="font-semibold text-[24px] leading-[29px]">Introduction</h2>
          <br />
          <p  className="font-semibold text-[15px] leading-[29px]">
            This Cookie Policy explains how JB Sittner Trucking and its
            affiliates (collectively "JB Sittner Trucking", "we", "us", and
            "ours"), use cookies and similar technologies to recognize you when
            you visit our website, including without limitation
            https://www.jbsittnertruckingllc.com/ and any related URLs, mobile
            or localized versions and related domains / sub-domains
            ("Websites"). It explains what these technologies are and why we use
            them, as well as the choices for how to control them.
          </p>
          <br />
          <h2           className="font-semibold text-[24px] leading-[29px]">What is a cookie?</h2>
          <br />
          <p  className="font-semibold text-[15px] leading-[29px]">
            A cookie is a small text file that is stored on your computer or
            other internet connected device in order to identify your browser,
            provide analytics, remember information about you such as your
            language preference or login information. They're completely safe
            and can't be used to run programs or deliver viruses to your device.
          </p>
          <br />
          <h2           className="font-semibold text-[24px] leading-[29px]">Why do we use cookies?</h2>
          <br />
          <p  className="font-semibold text-[15px] leading-[29px]">
            We use first party and/or third party cookies on our website for
            various purposes such as:
          </p>
          <br />
          <ul>
            <li>
              To facilitate the operation and functionality of our website;
            </li>
            <li>
              To improve your experience of our website and make navigating
              around them quicker and easier;
            </li>
            <li>
              To allow us to make a bespoke user experience for you and for us
              to understand what is useful or of interest to you;
            </li>
            <li>
              To analyze how our website is used and how best we can customize
              it;
            </li>
            <li>
              To identify future prospects and personalize marketing and sales
              interactions with it;
            </li>
            <li>
              To facilitate the tailoring of online advertising to your
              interests.
            </li>
          </ul>
          <br />
          <h2           className="font-semibold text-[24px] leading-[29px]">What type of cookies does JB Sittner Trucking use?</h2>
          <br />
          <p  className="font-semibold text-[15px] leading-[29px]">
            Cookies can either be session cookies or persistent cookies. A
            session cookie expires automatically when you close your browser. A
            persistent cookie will remain until it expires or you delete your
            cookies. Expiration dates are set in the cookies themselves; some
            may expire after a few minutes while others may expire after
            multiple years. Cookies placed by the website you’re visiting are
            called “first party cookies”.
          </p>
          <br />
          <p  className="font-semibold text-[15px] leading-[29px]">
            Strictly Necessary cookies are necessary for our website to function
            and cannot be switched off in our systems. They are essential in
            order to enable you to navigate around the website and use its
            features. If you remove or disable these cookies, we cannot
            guarantee that you will be able to use our website.
          </p>
          <br />
          <p  className="font-semibold text-[15px] leading-[29px]">We use the following types of cookies in our website:</p>
          <br />
          <h2           className="font-semibold text-[24px] leading-[29px]">Essential Cookies</h2>
          <br />
          <p  className="font-semibold text-[15px] leading-[29px]">
            We use essential cookies to make our website work. These cookies are
            strictly necessary to enable core functionality such as security,
            network management, your cookie preferences and accessibility.
            Without them you wouldn't be able to use basic services. You may
            disable these by changing your browser settings, but this may affect
            how the Websites function.
          </p>
          <br />
          <h2           className="font-semibold text-[24px] leading-[29px]">Performance and Functionality Cookies</h2>
          <br />
          <p  className="font-semibold text-[15px] leading-[29px]">
            These cookies are used to enhance the performance and functionality
            of our website but are non-essential to their use. However, without
            these cookies, certain functionality like videos may become
            unavailable or you would be required to enter your login details
            every time you visit the website as we would not be able to remember
            that you had logged in previously.
          </p>
          <br />
          <h2           className="font-semibold text-[24px] leading-[29px]">How you can manage cookies?</h2>
          <br />
          <p  className="font-semibold text-[15px] leading-[29px]">
            Most browsers allow you to control cookies through their 'settings'
            preferences. However, if you limit the ability of websites to set
            cookies, you may worsen your overall user experience, since it will
            no longer be personalized to you. It may also stop you from saving
            customized settings like login information. Browser manufacturers
            provide help pages relating to cookie management in their products.
          </p>
          <br />
          <p  className="font-semibold text-[15px] leading-[29px]">
            Browser manufacturers provide help pages relating to cookie
            management in their products. Please see below for more information.
          </p>
          <br />
          <ul>
            <li>Google Chrome</li>
            <li>Internet Explorer</li>
            <li>Mozilla Firefox</li>
            <li>Safari (Desktop)</li>
            <li>Safari (Mobile)</li>
            <li>Android Browser</li>
            <li>Opera</li>
            <li>Opera Mobile</li>
          </ul>
          <br />
          <h2           className="font-semibold text-[24px] leading-[29px]">Blocking and disabling cookies and similar technologies</h2>
          <br />
          <p  className="font-semibold text-[15px] leading-[29px]">
            Wherever you're located you may also set your browser to block
            cookies and similar technologies, but this action may block our
            essential cookies and prevent our website from functioning properly,
            and you may not be able to fully utilize all of its features and
            services. You should also be aware that you may also lose some saved
            information (e.g. saved login details, site preferences) if you
            block cookies on your browser. Different browsers make different
            controls available to you. Disabling a cookie or category of cookie
            does not delete the cookie from your browser, you will need to do
            this yourself from within your browser, you should visit your
            browser's help menu for more information.
          </p>
          <br />
          <h2           className="font-semibold text-[24px] leading-[29px]">Changes To Our Cookie Policy</h2>
          <br />
          <p  className="font-semibold text-[15px] leading-[29px]">
            We may change our Service and policies, and we may need to make
            changes to this Cookie Policy so that they accurately reflect our
            Service and policies. Unless otherwise required by law, we will
            notify you (for example, through our Service) before we make changes
            to this Cookie Policy and give you an opportunity to review them
            before they go into effect. Then, if you continue to use the
            Service, you will be bound by the updated Cookie Policy. If you do
            not want to agree to this or any updated Cookie Policy, you can
            delete your account.
          </p>
          <br />
          <h2           className="font-semibold text-[24px] leading-[29px]">Your Consent</h2>
          <p  className="font-semibold text-[15px] leading-[29px]">
            By using our website, registering an account, or making a purchase,
            you hereby consent to our Cookie Policy and agree to its terms.
          </p>
          <br />
          <h2           className="font-semibold text-[24px] leading-[29px]">Contact Us</h2>
          <p  className="font-semibold text-[15px] leading-[29px]">
            Don't hesitate to contact us if you have any questions regarding our
            Cookie Policy.
          </p>
          <br />
          <ul>
            <li>Via Email: office@jbsittner.com</li>
            <li>Via Phone Number: 9708972640</li>
            <li>Via this Link: https://www.jbsittnertruckingllc.com/</li>
            <li>Via this Address: 49600 CR 29.5 Nunn, Co, 80648</li>{" "}
          </ul>
        </>
      </div>
    </div>
  );
}
